import * as fs from "node:fs";
import * as path from "node:path";
import sharp from "sharp";
import { optimizeForWeb } from "../core/optimize";
import { writeSidecars } from "../core/sidecar";
import { resolveProvider } from "./gen";

/**
 * Edit an existing asset in place (img2img): the current file is the
 * base, the description says what to change, the result overwrites the
 * same path so code references stay valid.
 *
 * regen = new random take on the same brief; edit = keep this take,
 * adjust it.
 */
export async function runEdit(
  file: string,
  opts: { desc: string; provider?: string; model?: string; quality: string }
): Promise<void> {
  const out = path.resolve(file);
  if (!fs.existsSync(out)) {
    throw new Error(`${out} not found — edit needs an existing image file as its base.`);
  }

  // sidecar is optional here: files not generated by wda can be edited too
  const metaFile = out.replace(/\.[^.]+$/, "") + ".meta.json";
  const meta = fs.existsSync(metaFile) ? JSON.parse(fs.readFileSync(metaFile, "utf8")) : {};

  let size: string = meta.size;
  if (!size) {
    const m = await sharp(out).metadata();
    size = `${m.width}x${m.height}`;
  }
  const transparent = meta.transparent ?? false;

  // lean prompt on purpose: the base image already carries composition and
  // style, re-injecting the full type template would fight the original
  const prompt = [
    "Apply exactly this change to the image:",
    opts.desc.trim(),
    "",
    "Keep the overall composition, style, and all parts not covered by the change as close to the original as possible.",
    transparent ? "Preserve the transparent background (alpha channel)." : "",
    "No text, letters, numbers, logos, or watermarks anywhere in the image.",
  ]
    .filter(Boolean)
    .join("\n");

  const provider = resolveProvider(opts.provider);
  const image = await provider.generate({
    prompt,
    size,
    transparent,
    model: opts.model,
    baseImage: out,
  });
  const optimized = await optimizeForWeb(image.buffer, out, size, parseInt(opts.quality, 10));

  fs.writeFileSync(out, optimized.buffer);
  writeSidecars({
    type: meta.type ?? "background",
    desc: meta.desc ?? opts.desc,
    output: out,
    provider: provider.name,
    model: image.model,
    size,
    format: optimized.format,
    bytes: optimized.buffer.length,
    transparent,
    editDesc: opts.desc,
    prompt,
  });

  const kb = (optimized.buffer.length / 1024).toFixed(0);
  console.log(`wda: edited ${path.relative(process.cwd(), out)} (${optimized.format}, ${kb}KB)`);
}
