import * as fs from "node:fs";
import * as path from "node:path";
import { runGen } from "./gen";

/**
 * Regenerate one existing asset from its .meta.json sidecar.
 * The output path stays the same, so page code referencing the file
 * needs no change. Pass --desc to steer the result, otherwise the
 * original description is reused as-is.
 */
export async function runRegen(
  file: string,
  opts: { desc?: string; provider?: string; model?: string; quality?: string }
): Promise<void> {
  const out = path.resolve(file);
  const metaFile = out.replace(/\.[^.]+$/, "") + ".meta.json";
  if (!fs.existsSync(metaFile)) {
    throw new Error(
      `${metaFile} not found. regen needs the .meta.json sidecar written by wda gen; ` +
        `for files not generated by wda, use wda gen with --overwrite instead.`
    );
  }
  const meta = JSON.parse(fs.readFileSync(metaFile, "utf8"));

  await runGen(meta.type, {
    desc: opts.desc || meta.desc,
    out,
    provider: opts.provider ?? undefined,
    model: opts.model,
    size: meta.size,
    quality: opts.quality || "82",
    transparent: meta.transparent,
    scene: meta.scene,
    overwrite: true,
    dryRun: false,
  });
}
